name: Build and Deploy Development
on:
  push:
    branches:
      - main

jobs:
  terragrunt-check:
    name: Run Terragrunt Check
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    steps:
      - uses: actions/checkout@v4
      
      - name: Run terragrunt check
        run: |
          echo "terrgrunt check run"
          sleep 10

  terragrunt-plan:
    name: Run Terragrunt Plan
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    needs:
      - terragrunt-check
    steps:
      - uses: actions/checkout@v4
      
      - name: Run terragrunt plan
        run: |
          echo "terrgrunt plan run"
          sleep 10

  code-build:
    name: Build Code
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    steps:
      - uses: actions/checkout@v4
      
      - name: Build code
        run: |
          echo "code built"
          sleep 10

  code-package:
    name: Package Code
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    needs:
      - code-build
    steps:
      - uses: actions/checkout@v4
      
      - name: Package code
        run: |
          echo "code packaged"
          sleep 10

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    needs:
      - code-package
      - terragrunt-plan
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy code
        run: |
          echo "code deployed"
          sleep 10

  e2e-tests:
    name: Run E2E Tests
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Run e2e tests
        run: |
          echo "e2e tests run"
          sleep 10