name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

      - name: Trigger Build and Deploy Workflow on main branch
        if: steps.release.outputs.releases_created == 'false'
        run: |
          echo "No release created. Triggering Build and Deploy workflow."
          gh workflow run build-deploy-development.yml --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          release-type: simple